# Generated by Django 4.2.7 on 2023-11-05 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('post', models.TextField()),
                ('rating', models.CharField(choices=[('★', '1-Star Rating'), ('★★', '2-Star Rating'), ('★★★', '3-Star Rating'), ('★★★★', '4-Star Rating'), ('★★★★★', '5-Star Rating'), ('★★★★★★', '6-Star Rating')], max_length=200)),
                ('team', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='nba_forum.team')),
            ],
        ),
    ]
